# Faster linking for development builds
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# Enable dynamic linking for Bevy (much faster incremental builds)
[env]
CARGO_FEATURE_DYNAMIC_LINKING = "1"